# Generated by Django 4.1.2 on 2022-11-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.IntegerField()),
                ("Confirm_password", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phonenumber", models.IntegerField(max_length=10)),
                (
                    "userstatus",
                    models.SmallIntegerField(choices=[(0, "Inactive"), (1, "Active")]),
                ),
            ],
        ),
    ]
