# Generated by Django 4.1.2 on 2022-11-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_alter_regmodel_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regmodel",
            name="Confirm_password",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="regmodel",
            name="password",
            field=models.CharField(max_length=50),
        ),
    ]
