# Generated by Django 4.1.2 on 2022-11-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_alter_regmodel_confirm_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="logModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logId", models.IntegerField()),
                ("userID", models.IntegerField()),
                ("Ip", models.IntegerField()),
                ("date", models.IntegerField()),
                ("time", models.TimeField()),
                ("session", models.IntegerField()),
                ("Logout", models.TimeField()),
            ],
        ),
    ]
